### ISSUE TITLE
revc could be better.

### ISSUE THREAD

**Issue by Droogans** [rbcasperson/rosalind#22]
You're taking the index of each character in the input string, then manipulating the contents of a list at that position as you iterate over the input.

You can do better than this. Basically, if you find yourself writing code like this, there's almost always a better way to do it:

``` py
def print_in_loop(thing_that_is_iterable):
    for index in range(len(thing_that_is_iterable)):
        print thing_that_is_iterable[index]

>>> print_in_loop('andrew')
a
n
d
r
e
w
```

You could accomplish the same thing with this.

``` py
for item in thing_that_is_iterable:
    print item
```

Given that, you have another issue: you're manipulating a list while iterating over it. [This is a bad practice](http://stackoverflow.com/a/6260097/881224). Make a copy of the list and apply your transformations (or _ahem_, maybe..._translations_?) to that list instead.

**Comment by rbcasperson** [comment]
Yes, this one was a little tricky to think through. I'll try to find a way to make it better. My thought was that if I try to replace every "A" with "T", then every "T" with "A", everything that started as an "A" or a "T" would now be an "A".

```
work_list = "AAAAATTATTA"
work_list.replace("A", "T")
work_list.replace("T", "A")

>>> print work_list
"AAAAAAAAAAA"
```

That was just my original thinking, so I went with my solution as a work around. Let me see if I can make it work with good practice and I'll get back to you.

**Comment by Droogans** [comment]
> Make a copy of the list and apply your transformations (or ahem, maybe...translations?) to that list instead.

http://stackoverflow.com/a/21038977/881224
